spring:
  redis:
    host: localhost
    port: 6379

  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
    open-in-view: false

    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000
        use_sql_comments: true

  datasource:
    username: connectuser
    password: connect123!@#
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/idus?serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&characterEncoding=utf8
    maximumPoolSize: 100
    minimumIdle: 100

  logging.level:
    org.hibernate.SQL: debug
    org.higernate.type: trace

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

server:
  port: 8080

jwt:
  secret-key: "idus"